# Generated by Django 4.1 on 2024-05-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220124_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
